### ISSUE TITLE
[Latest release] Device reboot and saved data not visible

### ISSUE THREAD

**Issue by MaxInve** [LiquidFenrir/WifiManager#4]
Device: New 3DS
CFW: Luma 9.0

When I exit from the application, both from the home menu and with the start button, the app reboot all the sistem, with a little black screen freeze who takes about half a minute.

Also, the saved slot arent showed in the bottom screen, like whith the name I gived it or anything else. I don't known if this last is a true issue or just a not present feature.

https://i.imgur.com/Uy2vxmO.png

**Comment by LiquidFenrir** [comment]
the second one is being fixed, and the first one is almost normal - it reboots when exiting like system settings does, but it should only take about 5 seconds. are you using the cia or the 3dsx?

**Comment by MaxInve** [comment]
I'm using the .cia
Also now with the 1.1.2 version It take 10-15 seconds for the reboot

**Comment by LiquidFenrir** [comment]
That's more reasonable already, do you have a large (64 or 128GB) sd card? If so, your boot times should normally be long and a long reboot like that shouldnt be weird. it doesnt make sense for it to be on the application's side

**Comment by MaxInve** [comment]
unfortunately my SD card is just an 8gb one XD

Also I've tried rebooting the console with Quickreboot and rosalina, and the last one take the same time of your for the reboot, so I think it's just an "issue" of my 3ds

**Comment by LiquidFenrir** [comment]
indeed, sounds like a problem with your console, so I'm closing this if you dont mind
